const ALL_GENRES = [
  'Art',
  'Biography',
  'Business',
  `Children's`,
  'Christian',
  'Classics',
  'Comics',
  'Cookbooks',
  'Ebooks',
  'Fantasy',
  'Fiction',
  'Graphic Novels',
  'Historical Fiction',
  'History',
  'Horror',
  'Memoir',
  'Music',
  'Mystery',
  'Nonfiction',
  'Poetry',
  'Psychology',
  'Romance',
  'Science',
  'Science Fiction',
  'Self Help',
  'Sports',
  'Thriller',
  'Travel',
  'Young Adult',
] as const;

type Genre = (typeof ALL_GENRES)[number];

export default Genre;
